<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="newsletter-wrap">
    <div class="newsletter-container">
        <div class="newsletter-label">
            <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 width="45.73px" height="45.73px" viewBox="0 0 25.73 25.73" style="enable-background:new 0 0 25.73 25.73;" xml:space="preserve"
            >
                <g>
                    <g>
                    <path d="M24.408,0.597L0.706,13.026c-0.975,0.511-0.935,1.26,0.088,1.665l3.026,1.196c1.021,0.404,2.569,0.185,3.437-0.494
                        L20.399,5.03c0.864-0.681,0.957-0.58,0.206,0.224l-10.39,11.123c-0.753,0.801-0.529,1.783,0.495,2.182l0.354,0.139
                        c1.024,0.396,2.698,1.062,3.717,1.478l3.356,1.366c1.02,0.415,1.854,0.759,1.854,0.765c0,0.006,0.006,0.025,0.011,0.026
                        c0.005,0.002,0.246-0.864,0.534-1.926L25.654,1.6C25.942,0.537,25.383,0.087,24.408,0.597z"/>
                    <path d="M10.324,19.82l-2.322-0.95c-1.018-0.417-1.506,0.072-1.084,1.089c0.001,0,2.156,5.194,2.096,5.377
                        c-0.062,0.182,2.068-3.082,2.068-3.082C11.684,21.332,11.342,20.237,10.324,19.82z"/>
                    </g>
                </g>
            </svg>
            <div class="label-content">
                <h3>Sign up for our newsletter</h3>
                <span class="subscribe-sale">and enjoy -15% off your first purchase!</span>
            </div>
        </div>
        <div class="block newsletter">
            <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
            <div class="content">
                <form class="form subscribe"
                      novalidate
                      action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                      method="post"
                      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                      id="newsletter-validate-detail">
                    <div class="field newsletter">
                        <div class="control">
                            <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                                <input name="email" type="email" id="newsletter"
                                       placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                                       data-mage-init='{"mage/trim-input":{}}'
                                       data-validate="{required:true, 'validate-email':true}"
                                />
                            </label>
                        </div>
                    </div>
                    <div class="actions">
                        <button class="action subscribe primary"
                                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                                type="submit"
                                aria-label="Subscribe">
                            <span class="sub-m"><?= $block->escapeHtml(__('Subscribe')) ?></span>
                            <span class="sub-s"><?= $block->escapeHtml(__('GO')) ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>

<script>
    require([
        'jquery',
        'jquery/ui'
    ], function ($) {
        const w = 768;

        $(document).ready(function (){
            _sub(w);
            $(window).resize(function(){
                _sub(w);
            });
        });
        function _sub(width) {
            if ($(window).width() <= width) {
                $('.sub-s').css('display','block');
                $('.sub-m').css('display','none');
            } else {
                $('.sub-s').css('display','none');
                $('.sub-m').css('display','block');
            }
        }
    })
</script>
