<li class="level0 nav-1 category-item first level-top ui-menu-item" role="presentation">
    <a href="#" class="level-top ui-corner-all" id="ui-id-1" tabindex="-1" role="menuitem">
        <span>FASHION</span>
    </a>
</li>
<li class="level0 category-item level-top ui-menu-item" role="presentation">
    <a href="#" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
        <span>ELECTRONICS</span>
    </a>
</li>
<li class="level0 category-item level-top ui-menu-item" role="presentation">
    <a href="#" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
        <span>GIFTS</span>
    </a>
</li>
<li class="level0 category-item level-top ui-menu-item" role="presentation">
    <a href="#" class="level-top ui-corner-all" id="ui-id-4" tabindex="-1" role="menuitem">
        <span>BOOKS</span>
    </a>
</li>
<li class="level0 category-item level-top ui-menu-item" role="presentation">
    <a href="#" class="level-top ui-corner-all" id="ui-id-5" tabindex="-1" role="menuitem">
        <span>AT HOME</span>
    </a>
</li>
<li class="level0 category-item last level-top ui-menu-item" role="presentation">
    <a href="#" class="level-top ui-corner-all" id="ui-id-6" tabindex="-1" role="menuitem">
        <span>MUSIC</span>
    </a>
</li>
